### ISSUE TITLE
кодировочка

### ISSUE THREAD

**Issue by Perevedko** [NewYaroslav/strange_pattern#1]
https://github.com/NewYaroslav/strange_pattern/blob/master/src/BPSW.hpp
присутствуют кракозябры

**Comment by Perevedko** [comment]
![2018-07-23 2 43 20](https://user-images.githubusercontent.com/1755224/43050953-306f82de-8e22-11e8-825d-49f4619368b6.png)

**Comment by mashed-potatoes** [comment]
Обычно при сохранении используется кодировка Windows 1251, а GitHub все отображает в UTF-8.

**Comment by NewYaroslav** [comment]
Изменил кодировку в файлах на UTF-8 без BOM
